[source]
type = "file"
[source.file]
path = "original.csv"
skip_header = true
[source.format.csv]
delimiter = ","
[[source.format.csv.columns]]
name = "id"
type = "int"
[[source.format.csv.columns]]
name = "name"
type = "string"

#[source.encoding.gzip]

#[confluence]

[flow]
type = "filter"

#[branch]

[sink]
#type = "file"
type = "numpy"
[sink.file]
path = "result.csv"
[sink.numpy]
cols = [ "id" ]
[sink.format.csv]
delimiter = "\t"
[[sink.format.csv.columns]]
name = "id"
type = "int"
[[sink.format.csv.columns]]
name = "name"
type = "string"
#[sink.encoding.gzip]