[source]
[source.format.csv]
[[source.format.csv.columns]]
name = "id"
type = "int"
[[source.format.csv.columns]]
name = "name"
type = "string"

#[source.encoding.gzip]

#[confluence]

[flow]

#[branch]

[sink]
[sink.format.csv]
delimiter = ","
#[sink.encoding.gzip]