[source.read_awesome_csv]
type = "file"
path = "original.csv"
[source.read_awesome_csv.format]
type = "csv"
delimiter = ","
skip_header = true
columns = [
  { name = "id", type = "double" },
  { name = "name", type = "string" }
]

[flow.construct_knn_graph]
type = "to_graph"
from = "read_awesome_csv"
[flow.construct_knn_graph.distance]
type = "raw"
column = "id"

[sink.write_awesome_tsv]
type = "file"
from = "construct_knn_graph"
[sink.write_awesome_tsv.format]
type = "csv"
delimiter = "\t"
columns = [] # all